---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-s3-credentials
data:
  secretKey: "<secretKey>"
  accessKey: "<accessKey>"
---
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: aws-s3-source
spec:
  template:
    spec:
      containers:
        - name: aws-s3-source
          image: quay.io/openshift-knative/aws-s3-source:1.0-SNAPSHOT
          env:
            - name: CAMEL_KAMELET_AWS_S3_SOURCE_BUCKET_NAME_OR_ARN
              value: "arn:aws:s3:::knative-camel-demo"
            - name: CAMEL_KAMELET_AWS_S3_SOURCE_REGION
              value: us-east-1
            - name: CAMEL_KAMELET_AWS_S3_SOURCE_SECRETKEY
              valueFrom:
                configMapKeyRef:
                  name: aws-s3-credentials
                  key: secretKey
            - name: CAMEL_KAMELET_AWS_S3_SOURCE_ACCESSKEY
              valueFrom:
                configMapKeyRef:
                  name: aws-s3-credentials
                  key: accessKey
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
