---
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: timer-source
spec:
  template:
    spec:
      containers:
        - name: timer-source
          image: quay.io/openshift-knative/timer-source:1.0-SNAPSHOT
          env:
            - name: CAMEL_KAMELET_TIMER_SOURCE_MESSAGE
              value: Hello from timer container source!
            - name: CAMEL_KAMELET_TIMER_SOURCE_PERIOD
              value: "2000"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
