---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timer-properties
data:
  message: "Hello from configmap!"
  period: "2000"
---
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: timer-source
spec:
  template:
    spec:
      containers:
        - name: timer-source
          image: quay.io/openshift-knative/timer-source:1.0-SNAPSHOT
          env:
            - name: CAMEL_KAMELET_TIMER_SOURCE_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: timer-properties
                  key: message
            - name: CAMEL_KAMELET_TIMER_SOURCE_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: timer-properties
                  key: period
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
