---
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: star-wars-source
spec:
  template:
    spec:
      containers:
        - name: star-wars-source
          image: quay.io/christophd/star-wars-source:1.0-SNAPSHOT
          env:
            - name: CAMEL_KAMELET_STAR_WARS_SOURCE_RESOURCE
              value: starships
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
